#### Import pandas library using alias pd.

In [1]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df. Use the first column as index.

In [2]:
df = pd.read_csv("data/Recipes.csv", index_col = 0)
df

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            NaN                       

#### Print the type of variable df.

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


#### Print the number of columns and number of rows of the df DataFrame.

In [4]:
df.shape

(150, 78)

#### What are the names of the columns in df?

In [5]:
df.columns

Index(['vegetarian', 'glutenFree', 'dairyFree', 'veryHealthy', 'healthScore',
       'aggregateLikes', 'id', 'title', 'pricePerServing', 'readyInMinutes',
       'servings', 'sourceUrl', 'CaloriesAmount', 'CaloriespercentOfDailyNeed',
       'FatAmount', 'FatpercentOfDailyNeed', 'SaturatedFatAmount',
       'SaturatedFatpercentOfDailyNeed', 'CarbohydratesAmount',
       'CarbohydratespercentOfDailyNeed', 'NetCarbohydratesAmount',
       'NetCarbohydratespercentOfDailyNeed', 'SugarAmount',
       'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2per

#### Rename column id to RecipeId. Drop column "veryHealthy".

In [6]:
### when you do "inplace" you don't need to assign the result into a new variable. inplace changes the dataframe itself.
nuevo_df = df.rename(columns = {'id':'RecipeId'}, inplace = True) 
nuevo_df = df.drop(['veryHealthy'], axis=1)
nuevo_df

vegetarian  glutenFree  dairyFree  healthScore  aggregateLikes  RecipeId  \
0          True        True       True          1.0               3    633998   
1          True        True      False          0.0               1    634426   
2         False       False      False          3.0               1    635085   
3          True       False       True          2.0               1    663229   
4         False        True      False         31.0               3    651437   
..          ...         ...        ...          ...             ...       ...   
145       False        True       True         18.0              13    638315   
146        True       False      False          1.0               2    656248   
147        True        True       True         93.0               2    637297   
148        True        True      False          5.0               1    659412   
149        True        True       True        100.0               4    647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  servings  ... VitaminB3Amount  \
0                45         8  ...            0.49   
1                45        10  ...             NaN   
2                45         5  ...            2.63   
3                45        12  ...            0.65   
4                45         8  ...            0.66   
..              ...       ...  ...             ...   
145              45         6  ...            0.53   
146              45        16  ...            0.21   
147              45         4  ...            4.77   
148              45         4  ...            1.15   
149              30         4  ...            0.21   

     VitaminB3percentOfDailyNeed  VitaminB1Amount  \
0                           2.44             0.03   
1                            NaN              NaN   
2                          13.13             0.32   
3                           3.26             0.10   
4                           3.29             0.07   
..                           ...              ...   
145                         2.67             0.15   
146                         1.07             0.03   
147                        23.83             0.45   
148                         5.73             0.12   
149                         1.05              NaN   

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81   
1                            NaN            NaN                        NaN   
2                          21.09         100.80                      10.08   
3                           6.47          26.79                       2.68   
4                           4.64         162.84                      16.28   
..                           ...            ...                        ...   
145                        10.23         102.67                      10.27   
146                         1.68          19.82                       1.98   
147                        29.70         141.16                      14.12   
148                         7.85          55.64                  

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. a.Are there any other columns in this dataset that you would consider a candidate for the index column? b. Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        a.What happens if you wanted to rename a column that is not there?
        b.What happens if you set the argument inplace=True? 

In [7]:
#1a. Maybe the index could be RecipeId, just because it might be a non repeted number in the column
#1b. Because some columns might not have a name/string 

#2b. With inplace nothing happens
otro_nuevo_df = df.rename(columns = {'Silvi':'Silvina'}, inplace = True)
otro_nuevo_df

In [8]:
#2a. (without inplace) Nothing happens, no error
otro_nuevo_df = df.rename(columns = {'Silvi':'Silvina'})
otro_nuevo_df

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes  RecipeId  \
0                 3    633998   
1                 1    634426   
2                 1    635085   
3                 1    663229   
4                 3    651437   
..              ...       ...   
145              13    638315   
146               2    656248   
147               2    637297   
148               1    659412   
149               4    647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            Na

In [9]:

### Good answers and good job for trying things out ... 
### 1b could also be because it's more difficult to access them with a string as index


#### Import pandas library using alias pd.

In [10]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [11]:
df_ex1 = pd.read_csv("data/Recipes.csv", index_col = 0)
df_ex1

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            NaN                       

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [12]:
#1
df_ex1["vegetarian"][33] ### DONE.remember the 0-based index :) You checked the 35th recipe. 

True

In [13]:
#2
df_ex1.iloc[33,0] ### DONE.remember the 0-based index :) You checked the 35th recipe. 

True

In [14]:
#3
df_ex1.iloc[ 33:34  , 0 : 1] ### DONE.remember the 0-based index :) You checked the 35th recipe. 

vegetarian
33        True

In [15]:
#4
df_ex1.loc[33,"vegetarian"] ### DONE.remember the 0-based index :) You checked the 35th recipe. 

True

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [16]:
#checking the names of the columns
df_ex1.columns

Index(['vegetarian', 'glutenFree', 'dairyFree', 'veryHealthy', 'healthScore',
       'aggregateLikes', 'id', 'title', 'pricePerServing', 'readyInMinutes',
       'servings', 'sourceUrl', 'CaloriesAmount', 'CaloriespercentOfDailyNeed',
       'FatAmount', 'FatpercentOfDailyNeed', 'SaturatedFatAmount',
       'SaturatedFatpercentOfDailyNeed', 'CarbohydratesAmount',
       'CarbohydratespercentOfDailyNeed', 'NetCarbohydratesAmount',
       'NetCarbohydratespercentOfDailyNeed', 'SugarAmount',
       'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2per

In [17]:
#taking the columns I want, no order defined
df_ex1a = pd.read_csv('data/Recipes.csv', usecols = ['title','pricePerServing','vegetarian'])
df_ex1a

vegetarian                                              title  \
0          True                          Banana Blueberry Pancakes   
1          True            Basil and Orange Confit Compound Butter   
2         False                           Black Bottom Banana Bars   
3          True                The Best Raw Chocolate Chip Cookies   
4         False                Mediterranean Spinach Artichoke Dip   
..          ...                                                ...   
145       False       Chicken Sausage, White Bean and Cabbage Soup   
146        True                                Pinot Noir Brownies   
147        True                          Cauliflower Chickpea Stew   
148        True  Sautéed Balsamic Green Beans With Cherry Tomatoes   
149        True        Indian-Style Dill and Turmeric Potato Salad   

     pricePerServing  
0              55.79  
1              15.07  
2              78.85  
3              54.64  
4             115.26  
..               ...  
145           196.23  
146            65.76  
147           139.28  
148           101.81  
149           117.24  

[150 rows x 3 columns]

In [21]:
# oh, yes!
cols_to_use = ['title','pricePerServing','vegetarian']
df_ex2 = pd.read_csv('data/Recipes.csv', index_col=False, usecols= cols_to_use)[cols_to_use]

df_ex2

title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     vegetarian  
0          True  
1          True  
2         False  
3          True  
4         False  
..          ...  
145       False  
146        True  
147        True  
148        True  
149        True  

[150 rows x 3 columns]

In [20]:
###DONE. Good job on printing the right columns! Can you try and do it without re-reading the file?
### a hint would be to use a slicing method like .loc you can try and google how to slice multiple columns in pandas
df_ex1.loc[:, ['title','pricePerServing','vegetarian']]

title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     vegetarian  
0          True  
1          True  
2         False  
3          True  
4         False  
..          ...  
145       False  
146        True  
147        True  
148        True  
149        True  

[150 rows x 3 columns]

#### And now the same for recipes number from 24 to 29

In [22]:
df_ex2.iloc[24:30]

title  pricePerServing  vegetarian
24  Green Beans with Garlic Chips            83.90        True
25     Pandan Thumbprint Biscuits            54.26       False
26                  Lamb Moussaka           528.50       False
27         Easy Eggplant Parmesan           195.51        True
28                      Peach Pie           173.52        True
29                     Kappa Maki            72.94        True

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

In [23]:
df.loc[0,"readyInMinutes"] 

45

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others. 

In [24]:
#is the 10th included in the row?
df.iloc[ 98:100  ,  :10]

### the 10 is the column index, not the row :) and you can see in your output it is excluded .. you get from 0 to 9
#### Tak. Yes, I meant column :)

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
98       False        True      False        False         21.0   
99       False        True      False        False         38.0   

    aggregateLikes  RecipeId                                title  \
98               7    643150         Fluffy frittata with spinach   
99               2    661522  Steak With Blue Cheese Sherry Sauce   

    pricePerServing  readyInMinutes  
98           155.49              45  
99           175.88              45

In [ ]:
### Great job solving the pandas homework! Give a try for the next part too! You should be able to solve the numpy part too :) 


### Class-exercise 2

In [26]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array 

In [27]:
mi_2d_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mi_3d_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

2. Create a 2X2 integer array and show it's dimensions

In [29]:
# The rank of the array is the number of dimensions? (I read that somewhere)
# A dimension in arrays is one level of array depth (nested arrays)
mi_2x2_array = np.array([[1, 2], [3, 4]])
print(mi_2x2_array.ndim)


2


3. Create a numpy array and  print the sum of third and fourth elements from the array 

In [30]:
mi_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14 , 15 , 16],[17, 18, 19, 20]])
#mi_array.sum(axis=0) me da la suma de cada fila
#mi_array.sum(axis=1) me da la suma de cada columna
#mi_array.sum(axis=2) me da error, obviamente

#sum of [9, 10, 11, 12] and [13, 14 , 15 , 16]
mi_array[2:4].sum()

100

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [31]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:4]

array([15, 20, 25])

In [33]:
# with negative num
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[-6:-3]

array([15, 20, 25])

5. Try example 4. using STEP method

In [34]:
# I don't think this is the right solution
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:4:1]

array([15, 20, 25])

6. Create a integer array and change data type from integer to boolean



In [38]:
#np.array([0,1,0,1,2,3],dtype=bool)
mi_int_array = np.array([0,1,0,1,2,3],dtype=int)

mi_int_array2 = mi_int_array.astype(bool)
mi_int_array2

#Why with the following the type given is ndarray and not boolean?

#type(mi_int_array2) 

array([False,  True, False,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [39]:
nuevo_arr = np.array([1, 2, 3, 4, 5])

print(nuevo_arr.shape)

(5,)


8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [40]:
#it gives the index and not the element .....and it also gives the data type, why?
arr_todos = np.array([16, 8, 3, 7, 15, 24])

arr_pares = np.where(arr_todos %2 == 0)

print(arr_pares)

(array([0, 1, 5], dtype=int64),)


9. Create a numpy array of 5 person names and sort the values alpbabetically

In [41]:
nombres_de_a_z = np.array(["Juana", "Flavia", "Pablo", "Carlos", "Valeria"])
print(np.sort(nombres_de_a_z))

['Carlos' 'Flavia' 'Juana' 'Pablo' 'Valeria']


10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [42]:
array_numeros = np.array([3, 2, 0, 1])
correcto = np.sort(array_numeros)
correcto

array([0, 1, 2, 3])