#### Import pandas library using alias pd.

In [26]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df. Use the first column as index.

In [27]:
df = pd.read_csv('data/recipes.csv', index_col=0)
df

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            NaN                       

#### Print the type of variable df.

In [28]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


#### Print the number of columns and number of rows of the df DataFrame.

In [29]:
df.shape

(150, 78)

#### What are the names of the columns in df?

In [30]:
df.columns

Index(['vegetarian', 'glutenFree', 'dairyFree', 'veryHealthy', 'healthScore',
       'aggregateLikes', 'id', 'title', 'pricePerServing', 'readyInMinutes',
       'servings', 'sourceUrl', 'CaloriesAmount', 'CaloriespercentOfDailyNeed',
       'FatAmount', 'FatpercentOfDailyNeed', 'SaturatedFatAmount',
       'SaturatedFatpercentOfDailyNeed', 'CarbohydratesAmount',
       'CarbohydratespercentOfDailyNeed', 'NetCarbohydratesAmount',
       'NetCarbohydratespercentOfDailyNeed', 'SugarAmount',
       'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2per

#### Rename column id to RecipeId. Drop column "veryHealthy".

In [31]:
new_name = {'id':'RecipeId'}
df.rename(mapper=new_name, axis=1, inplace=True)
df.drop(labels='veryHealthy', axis=1, inplace=True)
df

vegetarian  glutenFree  dairyFree  healthScore  aggregateLikes  RecipeId  \
0          True        True       True          1.0               3    633998   
1          True        True      False          0.0               1    634426   
2         False       False      False          3.0               1    635085   
3          True       False       True          2.0               1    663229   
4         False        True      False         31.0               3    651437   
..          ...         ...        ...          ...             ...       ...   
145       False        True       True         18.0              13    638315   
146        True       False      False          1.0               2    656248   
147        True        True       True         93.0               2    637297   
148        True        True      False          5.0               1    659412   
149        True        True       True        100.0               4    647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  servings  ... VitaminB3Amount  \
0                45         8  ...            0.49   
1                45        10  ...             NaN   
2                45         5  ...            2.63   
3                45        12  ...            0.65   
4                45         8  ...            0.66   
..              ...       ...  ...             ...   
145              45         6  ...            0.53   
146              45        16  ...            0.21   
147              45         4  ...            4.77   
148              45         4  ...            1.15   
149              30         4  ...            0.21   

     VitaminB3percentOfDailyNeed  VitaminB1Amount  \
0                           2.44             0.03   
1                            NaN              NaN   
2                          13.13             0.32   
3                           3.26             0.10   
4                           3.29             0.07   
..                           ...              ...   
145                         2.67             0.15   
146                         1.07             0.03   
147                        23.83             0.45   
148                         5.73             0.12   
149                         1.05              NaN   

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81   
1                            NaN            NaN                        NaN   
2                          21.09         100.80                      10.08   
3                           6.47          26.79                       2.68   
4                           4.64         162.84                      16.28   
..                           ...            ...                        ...   
145                        10.23         102.67                      10.27   
146                         1.68          19.82                       1.98   
147                        29.70         141.16                      14.12   
148                         7.85          55.64                  

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. Are there any other columns in this dataset that you would consider a candidate for the index column? Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        What happens if you wanted to rename a column that is not there?
        What happens if you set the argument inplace=True? 

Answers:
1. Maybe the 'id' column could be used as index. It isn't always a good idea to use a string as index because it would be harder to access the items. 
2. If I want to rename a colum that is not there, then nothing would happen.
If I set the argument inplace=True, then the column in the df will be renamed.


In [12]:
### Depending how you access the column, an error might be thrown if you try to rename something that doesn't exist

#### Import pandas library using alias pd.

In [7]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [8]:
df_ex1 = pd.read_csv('data/recipes.csv', index_col=0)
df_ex1

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            NaN                       

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [9]:
df_ex1['vegetarian'][33]

True

In [10]:
df_ex1.vegetarian[33]

True

In [11]:
df_ex1.loc[33, 'vegetarian']

True

In [12]:
df_ex1.iloc[33,1]

True

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [13]:
df_ex1.loc[:,['title','pricePerServing','vegetarian']]

title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     vegetarian  
0          True  
1          True  
2         False  
3          True  
4         False  
..          ...  
145       False  
146        True  
147        True  
148        True  
149        True  

[150 rows x 3 columns]

#### And now the same for recipes number from 24 to 29

In [14]:
df_ex1.loc[23:28,'id']

23    635447
24    645416
25    654516
26    649225
27    641962
28    655145
Name: id, dtype: int64

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

In [15]:
df_ex1.iloc[23:28,6]

23    635447
24    645416
25    654516
26    649225
27    641962
Name: id, dtype: int64

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others. 

In [9]:
# I think I prefer loc method. 
# syntax: df.loc[row index, column index by title]

### Class-exercise 2

In [14]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array 

In [15]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])

2. Create a 2X2 integer array and show it's dimensions

In [16]:
array_2x2 = np.array([[1,2],[3,4]])
array_2x2.ndim

2

3. Create a numpy array and  print the sum of third and fourth elements from the array 

In [17]:
array = np.array([1,3,5,7,9])
print(array[2]+array[3])

12


4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [18]:
arr4 = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1], arr[3]) ### a slight typo here ;) 

NameError: name 'arr' is not defined

5. Try example 4. using STEP method

In [19]:
print(arr4[1:5:2])

[15 25]


6. Create a integer array and change data type from integer to boolean



In [20]:
np.array([0,1,0,1,2,3],dtype=bool)

array([False,  True, False,  True,  True,  True])

In [21]:
array_int = np.array([0,1,0,1,2,3])
array_bool = array_int.astype(bool)
array_bool

array([False,  True, False,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [22]:
arr7 = np.array([1, 2, 3, 4, 5])
arr7.shape

(5,)

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [23]:
arr8 = np.array([16, 8, 3, 7, 15, 24])
x = np.where(arr8 % 2 == 0)

print(x)

(array([0, 1, 5]),)


9. Create a numpy array of 5 person names and sort the values alpbabetically

In [24]:
arr9 = np.array(['Anfa','Bertha','Delta','Chris','Nova'])
np.sort(arr9)

array(['Anfa', 'Bertha', 'Chris', 'Delta', 'Nova'], dtype='<U6')

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [25]:
arr10 = np.array([3, 2, 0, 1])
np.sort(arr10)

array([0, 1, 2, 3])

In [ ]:
### Great job as always :) Not a lot of comments from my side as I everything looks super good and you went the extra mile too. 
### Keep it up!