#### Import pandas library using alias pd.

In [1]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df. Use the first column as index.

In [2]:
df = pd.read_csv("data/Recipes.csv")

#### Print the type of variable df.

In [3]:
type(df)

pandas.core.frame.DataFrame

#### Print the number of columns and number of rows of the df DataFrame.

In [4]:
df.info() 
#len(df.index) #prints no of rows
#len(df.columns) #prints no of columns


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 79 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Unnamed: 0                          150 non-null    int64  
 1   vegetarian                          150 non-null    bool   
 2   glutenFree                          150 non-null    bool   
 3   dairyFree                           150 non-null    bool   
 4   veryHealthy                         150 non-null    bool   
 5   healthScore                         150 non-null    float64
 6   aggregateLikes                      150 non-null    int64  
 7   id                                  150 non-null    int64  
 8   title                               150 non-null    object 
 9   pricePerServing                     150 non-null    float64
 10  readyInMinutes                      150 non-null    int64  
 11  servings                            150 non-n

#### What are the names of the columns in df?

In [5]:
print(df.columns)

Index(['Unnamed: 0', 'vegetarian', 'glutenFree', 'dairyFree', 'veryHealthy',
       'healthScore', 'aggregateLikes', 'id', 'title', 'pricePerServing',
       'readyInMinutes', 'servings', 'sourceUrl', 'CaloriesAmount',
       'CaloriespercentOfDailyNeed', 'FatAmount', 'FatpercentOfDailyNeed',
       'SaturatedFatAmount', 'SaturatedFatpercentOfDailyNeed',
       'CarbohydratesAmount', 'CarbohydratespercentOfDailyNeed',
       'NetCarbohydratesAmount', 'NetCarbohydratespercentOfDailyNeed',
       'SugarAmount', 'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
      

#### Rename column id to RecipeId. Drop column "veryHealthy".

In [18]:
new_df = pd.DataFrame(df)
new_df.rename(columns={"id":"RecipeID"})


Unnamed: 0  vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0             0        True        True       True        False          1.0   
1             1        True        True      False        False          0.0   
2             2       False       False      False        False          3.0   
3             3        True       False       True        False          2.0   
4             4       False        True      False        False         31.0   
..          ...         ...         ...        ...          ...          ...   
145         145       False        True       True        False         18.0   
146         146        True       False      False        False          1.0   
147         147        True        True       True         True         93.0   
148         148        True        True      False        False          5.0   
149         149        True        True       True         True        100.0   

     aggregateLikes  RecipeID  \
0                 3    633998   
1                 1    634426   
2                 1    635085   
3                 1    663229   
4                 3    651437   
..              ...       ...   
145              13    638315   
146               2    656248   
147               2    637297   
148               1    659412   
149               4    647875   

                                                 title  pricePerServing  ...  \
0                            Banana Blueberry Pancakes            55.79  ...   
1              Basil and Orange Confit Compound Butter            15.07  ...   
2                             Black Bottom Banana Bars            78.85  ...   
3                  The Best Raw Chocolate Chip Cookies            54.64  ...   
4                  Mediterranean Spinach Artichoke Dip           115.26  ...   
..                                                 ...              ...  ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23  ...   
146                                Pinot Noir Brownies            65.76  ...   
147                          Cauliflower Chickpea Stew           139.28  ...   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81  ...   
149        Indian-Style Dill and Turmeric Potato Salad           117.24  ...   

     VitaminB3Amount  VitaminB3percentOfDailyNeed VitaminB1Amount  \
0               0.49                         2.44            0.03   
1                NaN                          NaN             NaN   
2               2.63                        13.13            0.32   
3               0.65                         3.26            0.10   
4               0.66                         3.29            0.07   
..               ...                          ...             ...   
145             0.53                         2.67            0.15   
146             0.21                         1.07            0.03   
147             4.77                        23.83            0.45   
148             1.15                         5.73            0.12   
149             0.21                         1.05             NaN   

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81   
1                            NaN            NaN                        NaN   
2                          21.09         100.80                      10.08   
3                           6.47          26.79                       2.68   
4                           4.64         162.84                      16.28   
..                           ...            ...                        ...   
145                        10.23         102.67                      10.27   
146                         1.68          19.82                       1.98   
147                        29.70         141.16                      14.12   
148                         7.85          55.64                       5.56   

In [20]:
new_df.drop(['veryHealthy'], axis=1)

Unnamed: 0  vegetarian  glutenFree  dairyFree  healthScore  \
0             0        True        True       True          1.0   
1             1        True        True      False          0.0   
2             2       False       False      False          3.0   
3             3        True       False       True          2.0   
4             4       False        True      False         31.0   
..          ...         ...         ...        ...          ...   
145         145       False        True       True         18.0   
146         146        True       False      False          1.0   
147         147        True        True       True         93.0   
148         148        True        True      False          5.0   
149         149        True        True       True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            NaN                        NaN   
2   

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. Are there any other columns in this dataset that you would consider a candidate for the index column? Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        What happens if you wanted to rename a column that is not there?
        What happens if you set the argument inplace=True? 

#### Import pandas library using alias pd.

In [1]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [5]:
df_ex1 = pd.read_csv("data/Recipes.csv",index_col = 0)
df_ex1.set_index(['id'])

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
id                                                                    
633998        True        True       True        False          1.0   
634426        True        True      False        False          0.0   
635085       False       False      False        False          3.0   
663229        True       False       True        False          2.0   
651437       False        True      False        False         31.0   
...            ...         ...        ...          ...          ...   
638315       False        True       True        False         18.0   
656248        True       False      False        False          1.0   
637297        True        True       True         True         93.0   
659412        True        True      False        False          5.0   
647875        True        True       True         True        100.0   

        aggregateLikes                                              title  \
id                                                                          
633998               3                          Banana Blueberry Pancakes   
634426               1            Basil and Orange Confit Compound Butter   
635085               1                           Black Bottom Banana Bars   
663229               1                The Best Raw Chocolate Chip Cookies   
651437               3                Mediterranean Spinach Artichoke Dip   
...                ...                                                ...   
638315              13       Chicken Sausage, White Bean and Cabbage Soup   
656248               2                                Pinot Noir Brownies   
637297               2                          Cauliflower Chickpea Stew   
659412               1  Sautéed Balsamic Green Beans With Cherry Tomatoes   
647875               4        Indian-Style Dill and Turmeric Potato Salad   

        pricePerServing  readyInMinutes  servings  ... VitaminB3Amount  \
id                                                 ...                   
633998            55.79              45         8  ...            0.49   
634426            15.07              45        10  ...             NaN   
635085            78.85              45         5  ...            2.63   
663229            54.64              45        12  ...            0.65   
651437           115.26              45         8  ...            0.66   
...                 ...             ...       ...  ...             ...   
638315           196.23              45         6  ...            0.53   
656248            65.76              45        16  ...            0.21   
637297           139.28              45         4  ...            4.77   
659412           101.81              45         4  ...            1.15   
647875           117.24              30         4  ...            0.21   

        VitaminB3percentOfDailyNeed  VitaminB1Amount  \
id                                                     
633998                         2.44             0.03   
634426                          NaN              NaN   
635085                        13.13             0.32   
663229                         3.26             0.10   
651437                         3.29             0.07   
...                             ...              ...   
638315                         2.67             0.15   
656248                         1.07             0.03   
637297                        23.83             0.45   
659412                         5.73             0.12   
647875                         1.05              NaN   

        VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
id                                                                              
633998                         2.26          18.11                       1.81   
634426                          NaN            NaN                        NaN   
635085                        21.09         100.80                

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [4]:
df_ex1["vegetarian"][33]

df_ex1.loc[33,"vegetarian"]
df_ex1.iloc[33,1]

df_ex1.iat[33,1]

df_ex1.at[33,'vegetarian']

True

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [6]:
df_ex1[['title','pricePerServing', 'vegetarian']]

title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     vegetarian  
0          True  
1          True  
2         False  
3          True  
4         False  
..          ...  
145       False  
146        True  
147        True  
148        True  
149        True  

[150 rows x 3 columns]

#### And now the same for recipes number from 24 to 29

In [10]:
#method1: df_ex1[24:30]
df_ex1[['title','pricePerServing', 'vegetarian']].loc[24:29]

title  pricePerServing  vegetarian
24  Green Beans with Garlic Chips            83.90        True
25     Pandan Thumbprint Biscuits            54.26       False
26                  Lamb Moussaka           528.50       False
27         Easy Eggplant Parmesan           195.51        True
28                      Peach Pie           173.52        True
29                     Kappa Maki            72.94        True

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

In [12]:
df_ex1[-1:] #Displays last row from the data

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
149        True        True       True         True        100.0   

     aggregateLikes      id                                        title  \
149               4  647875  Indian-Style Dill and Turmeric Potato Salad   

     pricePerServing  readyInMinutes  ...  VitaminB3Amount  \
149           117.24              30  ...             0.21   

    VitaminB3percentOfDailyNeed  VitaminB1Amount  VitaminB1percentOfDailyNeed  \
149                        1.05              NaN                          NaN   

     CalciumAmount  CalciumpercentOfDailyNeed  AlcoholAmount  \
149          27.96                        2.8            NaN   

     AlcoholpercentOfDailyNeed  CaffeineAmount  CaffeinepercentOfDailyNeed  
149                        NaN             NaN                         NaN  

[1 rows x 78 columns]

In [13]:
df_ex1[:6] #displays Last 6 rows

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0        True        True       True        False          1.0   
1        True        True      False        False          0.0   
2       False       False      False        False          3.0   
3        True       False       True        False          2.0   
4       False        True      False        False         31.0   
5       False        True       True        False         30.0   

   aggregateLikes       id                                    title  \
0               3   633998                Banana Blueberry Pancakes   
1               1   634426  Basil and Orange Confit Compound Butter   
2               1   635085                 Black Bottom Banana Bars   
3               1   663229      The Best Raw Chocolate Chip Cookies   
4               3   651437      Mediterranean Spinach Artichoke Dip   
5               1  1096267                 Turkey Burgers with Slaw   

   pricePerServing  readyInMinutes  ...  VitaminB3Amount  \
0            55.79              45  ...             0.49   
1            15.07              45  ...              NaN   
2            78.85              45  ...             2.63   
3            54.64              45  ...             0.65   
4           115.26              45  ...             0.66   
5           387.61              30  ...            18.27   

  VitaminB3percentOfDailyNeed  VitaminB1Amount  VitaminB1percentOfDailyNeed  \
0                        2.44             0.03                         2.26   
1                         NaN              NaN                          NaN   
2                       13.13             0.32                        21.09   
3                        3.26             0.10                         6.47   
4                        3.29             0.07                         4.64   
5                       91.37             0.19                        12.44   

   CalciumAmount  CalciumpercentOfDailyNeed  AlcoholAmount  \
0          18.11                       1.81            NaN   
1            NaN                        NaN            NaN   
2         100.80                      10.08           0.28   
3          26.79                       2.68            NaN   
4         162.84                      16.28            NaN   
5          42.49                       4.25            NaN   

   AlcoholpercentOfDailyNeed  CaffeineAmount  CaffeinepercentOfDailyNeed  
0                        NaN             NaN                         NaN  
1                        NaN             NaN                         NaN  
2                       1.53            9.89                         3.3  
3                        NaN             NaN                         NaN  
4                        NaN             NaN                         NaN  
5                        NaN             NaN                         NaN  

[6 rows x 78 columns]

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others. 

In [16]:
df_ex1[30:] #starting from 30th element

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
30         True        True       True        False         17.0   
31         True        True      False        False          5.0   
32        False        True       True        False          6.0   
33         True        True       True        False         54.0   
34        False        True      False         True         78.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes       id  \
30                1  1096306   
31              249   716421   
32                1   652758   
33                2   641443   
34               15   661340   
..              ...      ...   
145              13   638315   
146               2   656248   
147               2   637297   
148               1   659412   
149               4   647875   

                                                 title  pricePerServing  \
30                            Vegan Chana Masala Curry           165.89   
31   Grilled Peach Melba with Vanilla Bean Frozen Y...           405.52   
32                                    Mussels Marinara           125.90   
33                           Detox Orange Carrot Juice           104.27   
34           Spinach Salad with Strawberry Vinaigrette           338.97   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
30               30  ...             2.14                       10.71   
31               45  ...             1.33                        6.63   
32               45  ...             0.90                        4.52   
33               45  ...             2.65                       13.26   
34               45  ...             6.03                       30.15   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
30              0.20                        13.09         154.27   
31              0.07                         4.70         184.10   
32              0.06                         4.19          41.74   
33              0.35                        23.48         168.53   
34              0.19                        12.65         221.46   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
30                       15.43            NaN                        NaN   
31                       18.41            NaN           

In [17]:
df_ex1[30:45]

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
30        True        True       True        False         17.0   
31        True        True      False        False          5.0   
32       False        True       True        False          6.0   
33        True        True       True        False         54.0   
34       False        True      False         True         78.0   
35       False        True      False        False          9.0   
36       False       False      False         True         57.0   
37        True        True      False        False         17.0   
38        True       False      False        False          9.0   
39        True        True       True        False          7.0   
40       False        True      False        False         12.0   
41        True       False      False        False          1.0   
42        True        True      False        False          2.0   
43       False       False      False        False         44.0   
44       False       False      False        False          0.0   

    aggregateLikes       id  \
30               1  1096306   
31             249   716421   
32               1   652758   
33               2   641443   
34              15   661340   
35               6   634605   
36               1   647124   
37               1   658495   
38               1   649300   
39               6  1098357   
40               7   641904   
41               1   657875   
42               8   655098   
43               1   622825   
44               1  1095774   

                                                title  pricePerServing  \
30                           Vegan Chana Masala Curry           165.89   
31  Grilled Peach Melba with Vanilla Bean Frozen Y...           405.52   
32                                   Mussels Marinara           125.90   
33                          Detox Orange Carrot Juice           104.27   
34          Spinach Salad with Strawberry Vinaigrette           338.97   
35                                   Beef Cottage Pie           113.45   
36         Homemade Thin Crust Pizza + Pesto + Potato           199.57   
37                   Roasted Asparagus with Egg Salad           217.78   
38  Latkes; Fried Vegetable Pancakes from Europe a...            58.55   
39                Three Ingredient Frozen Pina Colada           214.60   
40                              Easy Chicken Tandoori           151.89   
41                         Raspberry Jam Swirled Buns            28.09   
42                            Peach Coconut Ice Cream            72.45   
43                          Tortilla Burger Loco Vaca           407.86   
44                        Moist and Tender Lemon Cake            68.21   

    readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
30              30  ...             2.14                       10.71   
31              45  ...             1.33                        6.63   
32              45  ...             0.90                        4.52   
33              45  ...             2.65                       13.26   
34              45  ...             6.03                       30.15   
35              45  ...             3.31                       16.55   
36              45  ...             7.12                       35.59   
37              45  ...             2.17                       10.85   
38              45  ...             2.20                       10.98   
39               5  ...             1.05                        5.25   
40              45  ...             3.64                       18.18   
41              45  ...             1.47                        7.36   
42              45  ...             0.97                        4.84   
43              40  ...            12.82                       64.12   
44              35  ...             0.76                        3.81   

    VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
30             0.20          

In [20]:
df_ex1.loc[[5,35,135],:] #select specific 5, 35, 135 

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
5         False        True       True        False         30.0   
35        False        True      False        False          9.0   
135       False        True       True        False         13.0   

     aggregateLikes       id                                    title  \
5                 1  1096267                 Turkey Burgers with Slaw   
35                6   634605                         Beef Cottage Pie   
135               1   639843  Cod Fillet In Lemon Grass Shallot Sauce   

     pricePerServing  readyInMinutes  ...  VitaminB3Amount  \
5             387.61              30  ...            18.27   
35            113.45              45  ...             3.31   
135           307.35              45  ...             0.51   

    VitaminB3percentOfDailyNeed  VitaminB1Amount  VitaminB1percentOfDailyNeed  \
5                         91.37             0.19                        12.44   
35                        16.55             0.05                         3.33   
135                        2.54             0.10                         6.91   

     CalciumAmount  CalciumpercentOfDailyNeed  AlcoholAmount  \
5            42.49                       4.25            NaN   
35           45.50                       4.55            NaN   
135          72.79                       7.28            NaN   

     AlcoholpercentOfDailyNeed  CaffeineAmount  CaffeinepercentOfDailyNeed  
5                          NaN             NaN                         NaN  
35                         NaN             NaN                         NaN  
135                        NaN             NaN                         NaN  

[3 rows x 78 columns]

### Class-exercise 2

In [21]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array 

In [22]:
#Create 2d numpy integer array (3,2)
numpy_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

#Create 3d numpy integer array (4,2,3)

numpy_3d_array = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]],[[10,11,12],[12,13,14]],[[12,13,14],[14,15,16]]])
print(numpy_3d_array)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [12 13 14]]

 [[12 13 14]
  [14 15 16]]]


2. Create a 2X2 integer array and show it's dimensions

In [23]:
#Create 2d numpy integer array
array = np.array([[1, 2], [3, 4]])
array.ndim

2

3. Create a numpy array and  print the sum of third and fourth elements from the array 

In [24]:
def sum_of_2_elements(arr, index1, index2):
    return (arr[index1]) + (arr[index2])
    
numpy_array = np.array([1, 2, 3, 4, 5]) 
numpy_array[3]

sum_of_2_elements(numpy_array,2,3)

7

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [25]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:4]

array([15, 20, 25])

5. Try example 4. using STEP method

In [26]:
arr[1:4:2]

array([15, 25])

6. Create a integer array and change data type from integer to boolean



In [2]:
np.array([0,1,0,1,2,3],dtype=bool)

array([False,  True, False,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr.shape

(5,)

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [28]:
arr = [16, 8, 3, 7, 15, 24]
arr = np.array(arr)
arr[arr % 2 == 0]

array([16,  8, 24])

9. Create a numpy array of 5 person names and sort the values alpbabetically

In [30]:
np_array = ['Adhya','Advi','Vittu','Jhanu','Radhi']

np.sort(np_array)
#np_array.sort()
np_array

['Adhya', 'Advi', 'Vittu', 'Jhanu', 'Radhi']

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [31]:
arr = np.array([3, 2, 0, 1])
arr = np.sort(arr)
arr

array([0, 1, 2, 3])