#### Import pandas library using alias pd.

In [1]:
import pandas as pd

#### Load file 'recipes.csv' from the data subfolder and store it in a variable df. Use the first column as index.

In [2]:
df = pd.read_csv("data/recipes.csv", index_col = 0)

#### Print the type of variable df.

In [3]:
type(df)

pandas.core.frame.DataFrame

#### Print the number of columns and number of rows of the df DataFrame.

In [4]:
df.shape

(150, 78)

#### What are the names of the columns in df?

In [65]:
for col in df.columns:
    print(col)
#print(*df.columns)

vegetarian
glutenFree
dairyFree
veryHealthy
healthScore
aggregateLikes
RecipeId
title
pricePerServing
readyInMinutes
servings
sourceUrl
CaloriesAmount
CaloriespercentOfDailyNeed
FatAmount
FatpercentOfDailyNeed
SaturatedFatAmount
SaturatedFatpercentOfDailyNeed
CarbohydratesAmount
CarbohydratespercentOfDailyNeed
NetCarbohydratesAmount
NetCarbohydratespercentOfDailyNeed
SugarAmount
SugarpercentOfDailyNeed
CholesterolAmount
CholesterolpercentOfDailyNeed
SodiumAmount
SodiumpercentOfDailyNeed
ProteinAmount
ProteinpercentOfDailyNeed
FiberAmount
FiberpercentOfDailyNeed
VitaminB6Amount
VitaminB6percentOfDailyNeed
ManganeseAmount
ManganesepercentOfDailyNeed
SeleniumAmount
SeleniumpercentOfDailyNeed
PotassiumAmount
PotassiumpercentOfDailyNeed
VitaminB2Amount
VitaminB2percentOfDailyNeed
VitaminCAmount
VitaminCpercentOfDailyNeed
PhosphorusAmount
PhosphoruspercentOfDailyNeed
FolateAmount
FolatepercentOfDailyNeed
VitaminB5Amount
VitaminB5percentOfDailyNeed
MagnesiumAmount
MagnesiumpercentOfDailyNeed


#### Rename column id to RecipeId. Drop column "veryHealthy".

In [6]:
df = df.rename({'id': 'RecipeId'}, axis = 1)
new_df = df.drop('veryHealthy', axis = 1)
new_df

vegetarian  glutenFree  dairyFree  healthScore  aggregateLikes  RecipeId  \
0          True        True       True          1.0               3    633998   
1          True        True      False          0.0               1    634426   
2         False       False      False          3.0               1    635085   
3          True       False       True          2.0               1    663229   
4         False        True      False         31.0               3    651437   
..          ...         ...        ...          ...             ...       ...   
145       False        True       True         18.0              13    638315   
146        True       False      False          1.0               2    656248   
147        True        True       True         93.0               2    637297   
148        True        True      False          5.0               1    659412   
149        True        True       True        100.0               4    647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  servings  ... VitaminB3Amount  \
0                45         8  ...            0.49   
1                45        10  ...             NaN   
2                45         5  ...            2.63   
3                45        12  ...            0.65   
4                45         8  ...            0.66   
..              ...       ...  ...             ...   
145              45         6  ...            0.53   
146              45        16  ...            0.21   
147              45         4  ...            4.77   
148              45         4  ...            1.15   
149              30         4  ...            0.21   

     VitaminB3percentOfDailyNeed  VitaminB1Amount  \
0                           2.44             0.03   
1                            NaN              NaN   
2                          13.13             0.32   
3                           3.26             0.10   
4                           3.29             0.07   
..                           ...              ...   
145                         2.67             0.15   
146                         1.07             0.03   
147                        23.83             0.45   
148                         5.73             0.12   
149                         1.05              NaN   

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81   
1                            NaN            NaN                        NaN   
2                          21.09         100.80                      10.08   
3                           6.47          26.79                       2.68   
4                           4.64         162.84                      16.28   
..                           ...            ...                        ...   
145                        10.23         102.67                      10.27   
146                         1.68          19.82                       1.98   
147                        29.70         141.16                      14.12   
148                         7.85          55.64                  

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. Are there any other columns in this dataset that you would consider a candidate for the index column? Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        What happens if you wanted to rename a column that is not there?
        What happens if you set the argument inplace=True? 

In [7]:
#What happens if you wanted to rename a column that is not there?
text_drop = df.rename({'id': 'RecipentId'}, axis = 1)
text_drop # the program runs but there is no changing

#What happens if you set the argument inplace=True?
#Then it will be changed in the original dataframe

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes  RecipeId  \
0                 3    633998   
1                 1    634426   
2                 1    635085   
3                 1    663229   
4                 3    651437   
..              ...       ...   
145              13    638315   
146               2    656248   
147               2    637297   
148               1    659412   
149               4    647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            Na

#### Import pandas library using alias pd.

In [8]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [9]:
df_ex1 = pd.read_csv("data/recipes.csv", index_col = 0)

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [1]:
### Remember 0 based indexing
### numbering starts from 0, so a 33 reprsents a 34

df_ex1.loc[34, "vegetarian"]
#df_ex1.iloc[34,0] 
#df_ex1.iloc[34].vegetarian
#df_ex1["vegetarian"][34]

NameError: name 'df_ex1' is not defined

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [11]:
df_ex1.filter(items=['title', 'pricePerServing', 'vegetarian'])

title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     vegetarian  
0          True  
1          True  
2         False  
3          True  
4         False  
..          ...  
145       False  
146        True  
147        True  
148        True  
149        True  

[150 rows x 3 columns]

#### And now the same for recipes number from 24 to 29

In [12]:
df_ex1.filter(items=['title', 'pricePerServing', 'vegetarian']).iloc[24:30]

title  pricePerServing  vegetarian
24  Green Beans with Garlic Chips            83.90        True
25     Pandan Thumbprint Biscuits            54.26       False
26                  Lamb Moussaka           528.50       False
27         Easy Eggplant Parmesan           195.51        True
28                      Peach Pie           173.52        True
29                     Kappa Maki            72.94        True

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

In [13]:
df_ex1.filter(items=['pricePerServing', 'readyInMinutes', 'veryHealthy']).iloc[12:60]

pricePerServing  readyInMinutes  veryHealthy
12            74.24              45        False
13            59.65              45        False
14           220.53              45        False
15            99.58              45        False
16           157.95              45        False
17           168.13              45        False
18            71.80              75        False
19           416.91              45        False
20            74.69              45        False
21           370.04              30        False
22           102.10              45        False
23           270.38              45        False
24            83.90              45        False
25            54.26              45        False
26           528.50              45        False
27           195.51              45        False
28           173.52              45        False
29            72.94              45        False
30           165.89              30        False
31           405.52              45        False
32           125.90              45        False
33           104.27              45        False
34           338.97              45         True
35           113.45              45        False
36           199.57              45         True
37           217.78              45        False
38            58.55              45        False
39           214.60               5        False
40           151.89              45        False
41            28.09              45        False
42            72.45              45        False
43           407.86              40        False
44            68.21              35        False
45            92.09              55        False
46           488.56              85        False
47            32.39              45        False
48           201.03              45        False
49           143.45              45        False
50           101.43              14        False
51            78.52              45        False
52            92.26              45        False
53            97.28              45        False
54           190.36              45        False
55           310.01              45         True
56           103.25              45        False
57           101.81              45        False
58           191.47              45        False
59           244.88              10        False

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others. 

### Class-exercise 2

In [16]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array 

In [28]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]],  np.int32)
arr1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [25]:
arr2 = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
arr2

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

2. Create a 2X2 integer array and show it's dimensions

In [40]:
dimension_array = np.array([[1, 6], [4, 6]])
dimension_array.shape
#dimension_array.ndim

2

3. Create a numpy array and  print the sum of third and fourth elements from the array 

In [84]:
numpy_array = np.array([1, 6, 3, 2, 1, 5, 7])
numpy_array[[2, 3]].sum()

5

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [89]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:4]

array([20, 25, 30])

5. Try example 4. using STEP method

In [2]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:4:2]  
### this is a step function
### arr[0:7:2], go from 0 to 7 and take every 2nd item
"""
I didn't understand the difference between the 4th and 5th task, I tried to search for step method but I couldn't
find anything about it. I only found the arange but I wasn't sure if that is the right way to do it.
"""

NameError: name 'np' is not defined

6. Create a integer array and change data type from integer to boolean



In [47]:
np.array([0,1,0,1,2,3],dtype=bool)

array([False,  True, False,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [52]:
arr = np.array([1, 2, 3, 4, 5])
arr.shape

(5,)

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [90]:
arr_1 = np.array([16, 8, 3, 7, 15, 24])
arr_1[arr_1%2==0]

array([16,  8, 24])

9. Create a numpy array of 5 person names and sort the values alpbabetically

In [59]:
arr_2 = np.array(["Lise", "Magnus", "Jonas", "Sarah", "Bob"])
print(np.sort(arr_2))

['Bob' 'Jonas' 'Lise' 'Magnus' 'Sarah']


10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [61]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]
